# Generated by Django 4.1.3 on 2024-02-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='color',
            field=models.CharField(max_length=150, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
